-- Modify the rooms table
ALTER TABLE rooms
    ADD COLUMN view_type VARCHAR(50),
    ADD COLUMN has_private_bathroom BOOLEAN DEFAULT true,
    ADD COLUMN smoking BOOLEAN DEFAULT false,
    ADD COLUMN accessibility_features JSON,
    ADD COLUMN floor_level INT,
    ADD COLUMN has_balcony BOOLEAN DEFAULT false,
    ADD COLUMN has_kitchen BOOLEAN DEFAULT false,
    ADD COLUMN has_minibar BOOLEAN DEFAULT false,
    ADD COLUMN climate JSON,
    ADD COLUMN price_per_night DECIMAL(10,2),
    ADD COLUMN cancellation_policy VARCHAR(50),
    ADD COLUMN includes_breakfast BOOLEAN DEFAULT false,
    ADD COLUMN extra_bed_available BOOLEAN DEFAULT false,
    ADD COLUMN pets_allowed BOOLEAN DEFAULT false,
    ADD COLUMN images JSON,
    ADD COLUMN cleaning_frequency VARCHAR(50),
    ADD COLUMN has_toiletries BOOLEAN DEFAULT false,
    ADD COLUMN has_towels_linens BOOLEAN DEFAULT false,
    ADD COLUMN has_room_service BOOLEAN DEFAULT false,
    ADD COLUMN flooring_type VARCHAR(50),
    ADD COLUMN energy_saving_features JSON,
    ADD COLUMN status VARCHAR(20) DEFAULT 'available',
    MODIFY COLUMN room_type VARCHAR(50) NOT NULL,
    MODIFY COLUMN bed_type ENUM('Single Bed', 'Double Bed', 'Queen Bed', 'King Bed', 'Sofa Bed', 'Bunk Bed') NOT NULL,
    DROP COLUMN beds;
