name: overpass-api

services:
  overpass-api:
    image: wiktorn/overpass-api
    container_name: overpass-api
    ports:
      - "8080:80"
    volumes:
      - overpass-data:/db
    environment:
      - OVERPASS_META=yes
      - OVERPASS_MODE=init
      - OVERPASS_PLANET_URL=https://download.geofabrik.de/europe/romania-latest.osm.pbf
      # Europe dataset is large (~24GB) and will take significant time to import
      # For smaller regions, you could use:
      # - OVERPASS_PLANET_URL=https://download.geofabrik.de/europe/monaco-latest.osm.bz2
      - OVERPASS_DIFF_URL=https://download.openstreetmap.fr/replication/europe/romania/minute/
      - OVERPASS_RULES_LOAD=10
      - OVERPASS_UPDATE_SLEEP=60
    restart: unless-stopped
    # Resource limits for handling the large Europe dataset
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    # Increase shared memory size for large dataset processing
    shm_size: 2gb

volumes:
  overpass-data: 